// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projectef;

#nullable disable

namespace projectef.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20251226061555_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("projectef.src.models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f75b"),
                            Descripcion = "lorem ipsun door af terque cua fofvy ether who",
                            Name = "Actividades Pendientes",
                            Peso = 60
                        },
                        new
                        {
                            CategoryId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f752"),
                            Descripcion = "lorem ipsun door af terque cua fofvy ether who",
                            Name = "Actividades Personales",
                            Peso = 70
                        });
                });

            modelBuilder.Entity("projectef.src.models.TodoTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Create_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PriorityTask")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("task", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f751"),
                            CategoryId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f75b"),
                            Create_on = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PriorityTask = 1,
                            Title = "Pago de servicios Publicos"
                        },
                        new
                        {
                            TaskId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f759"),
                            CategoryId = new Guid("baed9063-a68c-4e94-8f55-19c2fc68f752"),
                            Create_on = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PriorityTask = 2,
                            Title = "Pago de servicios Privados"
                        });
                });

            modelBuilder.Entity("projectef.src.models.TodoTask", b =>
                {
                    b.HasOne("projectef.src.models.Category", "category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("projectef.src.models.Category", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
